[package]
name = "playground"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "playground"
path = "src/main.rs"

[dependencies]
reifydb = { workspace = true, features = ["sub_flow", "sub_tracing"] }
tokio = { workspace = true }
tracing-subscriber = {workspace = true}