[package]
name = "playground"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "playground"
path = "src/main.rs"

[dependencies]
reifydb = { workspace = true, features = ["sub_flow", "sub_tracing", "sub_server_ws"] }
reifydb-client = { workspace = true }
reifydb-catalog = { workspace = true }
reifydb-core = { workspace = true }
reifydb-engine = { workspace = true }
reifydb-transaction = { workspace = true }
reifydb-type = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = {workspace = true}