[package]
name = "reifydb-rqlv2"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "ReifyDB Query Language (RQL)"

[dependencies]
bumpalo = { workspace = true }
reifydb-catalog = { workspace = true }
reifydb-core = { workspace = true }
reifydb-function = { workspace = true }
reifydb-hash = { workspace = true }
reifydb-transaction = { workspace = true }
reifydb-type = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
reifydb = { workspace = true}
reifydb-testing = { workspace = true }
test_each_file = { workspace = true }