[package]
name = "reifydb-rqlv2"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "ReifyDB Query Language (RQL)"

[dependencies]

[dev-dependencies]