[package]
name = "reifydb-runtime"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true
edition.workspace = true
description = "Runtime infrastructure for ReifyDB"

[features]
default = []

[build-dependencies]
reifydb-build = { workspace = true }

[dependencies]
# Common dependencies
cfg-if = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
xxhash-rust = { workspace = true }
futures-util = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true }
rayon = { workspace = true }
crossbeam-channel = { workspace = true }
parking_lot = { workspace = true }
dashmap = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true, features = ["Window"] }
