[package]
name = "reifydb-cdc"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Change Data Capture module for ReifyDB"

[dependencies]
futures-util = { workspace = true }
reifydb-core = {workspace = true}
reifydb-engine = { workspace = true }
reifydb-sub-api = { workspace = true }
reifydb-transaction = { workspace = true }
reifydb-type = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }


[dev-dependencies]
reifydb-catalog = { workspace = true }
reifydb-store-transaction = { workspace = true }
