[package]
name = "reifydb-cdc"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Change Data Capture module for ReifyDB"

[dependencies]
crossbeam-channel = { workspace = true }
parking_lot = { workspace = true }
reifydb-core = { workspace = true }
reifydb-transaction = { workspace = true }
reifydb-type = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
reifydb-catalog = { workspace = true }
reifydb-engine = { workspace = true }
reifydb-store-transaction = { workspace = true }
reifydb-testing = { workspace = true }
test_each_file = { workspace = true }
