[package]
name = "testcontainer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "testcontainer"
path = "src/main.rs"

[dependencies]
reifydb = { workspace = true, features = ["sub_logging", "sub_server", "sub_flow"] }
