[package]
name = "testcontainer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "testcontainer"
path = "src/main.rs"

[dependencies]
reifydb = { workspace = true, features = ["sub_tracing", "sub_server_admin", "sub_server_http", "sub_server_ws", "sub_server_otel", "sub_flow"] }
tokio = { workspace = true }
tracing = { workspace = true }
num_cpus = { workspace = true }
