[package]
name = "reifydb-sub-task"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []

[dependencies]
tokio = { workspace = true }
dashmap = { workspace = true }
reifydb-core = { workspace = true }
reifydb-engine = { workspace = true }
reifydb-runtime = { workspace = true }
reifydb-sub-api = { workspace = true }
reifydb-transaction = { workspace = true }
reifydb-type = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
