[package]
name = "reifydb-sub-server"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
reifydb-core = { workspace = true }
reifydb-engine = { workspace = true }
reifydb-sub-api = { workspace = true }
reifydb-sub-worker = { workspace = true }
reifydb-type = { workspace = true }
reifydb-network = { workspace = true }

mio = { workspace = true }
slab = { workspace = true }
socket2 = { workspace = true }
urlencoding = { workspace = true }
core_affinity = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }

