[package]
name = "reifydb-sub-server"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Common infrastructure for HTTP and WebSocket server subsystems"

[features]
default = []

[dependencies]
reifydb-core = { workspace = true }
reifydb-engine = { workspace = true }
reifydb-runtime = { workspace = true }
reifydb-type = { workspace = true }

futures-util = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
num_cpus = { workspace = true }
tokio = { workspace = true }
