[package]
name = "reifydb-store-transaction"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Transaction storage for OLTP operations and recent data"

[dependencies]
reifydb-core = { workspace = true }
reifydb-testing = { workspace = true }
reifydb-type = { workspace = true }

parking_lot = { workspace = true }

rusqlite = { workspace = true, features = ["bundled"] }
uuid = { workspace = true }
