[package]
name = "reifydb-sub-flow"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reifydb-cdc = { workspace = true }
reifydb-core = { workspace = true }
reifydb-catalog = { workspace = true }
reifydb-engine = { workspace = true }
reifydb-hash = { workspace = true }
reifydb-rql = { workspace = true }
reifydb-sub-api = { workspace = true }
reifydb-transaction = {workspace = true}
reifydb-type = { workspace = true }

serde = { workspace = true }
serde_bytes = { workspace = true}
serde_json = { workspace = true }
bincode = { workspace = true }

parking_lot = { workspace = true}

[dev-dependencies]
reifydb-store-transaction = { workspace = true}
reifydb-transaction = { workspace = true}