[package]
name = "reifydb-rql"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "ReifyDB Query Language (RQL) parser and AST"

[dependencies]
reifydb-core = {workspace = true}
reifydb-catalog = { workspace = true }
reifydb-type = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
reifydb-testing = { workspace = true }
reifydb-catalog = { workspace = true }
reifydb-engine = { workspace = true }
test_each_file = { workspace = true }