[package]
name = "reifydb-rql"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "ReifyDB Query Language (RQL) parser and AST"

[features]
default = ["native"]
native = [
    "reifydb-catalog/native",
    "reifydb-core/native",
    "reifydb-transaction/native",
    "reifydb-type/native",
]
wasm = [
    "reifydb-catalog/wasm",
    "reifydb-core/wasm",
    "reifydb-transaction/wasm",
    "reifydb-type/wasm",
]

[dependencies]
reifydb-core = {workspace = true}
reifydb-catalog = { workspace = true }
reifydb-transaction = { workspace = true }
reifydb-type = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
postcard = { workspace = true }

[dev-dependencies]
reifydb-testing = { workspace = true }
reifydb-catalog = { workspace = true, features = ["native"] }
reifydb-engine = { workspace = true, features = ["tokio"] }
test_each_file = { workspace = true }
tokio = { workspace = true }