[package]
name = "reifydb-type"
authors.workspace = true
version.workspace = true
edition.workspace = true
license = "MIT"
repository.workspace = true
description = "Core type system and value representations for ReifyDB"

[features]
default = []

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

uuid = { workspace = true }
num-bigint = { workspace = true, features = ["serde"] }
bigdecimal = { workspace = true, features = ["serde"] }
num-traits = { workspace = true }

reifydb-runtime = { workspace = true }

[dev-dependencies]
postcard = { workspace = true }
tokio = { workspace = true}
