[package]
name = "reifydb-sub-tracing"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Tracing subsystem for ReifyDB using tracing_subscriber"

[dependencies]
reifydb-core = { workspace = true }
reifydb-engine = { workspace = true }
reifydb-sub-api = { workspace = true }
reifydb-transaction = { workspace = true }
reifydb-type = { workspace = true }

async-trait = {workspace = true}

# Tracing
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
reifydb-testing = { workspace = true }
