[package]
name = "reifydb-client-derive"
version.workspace = true
edition.workspace = true
authors.workspace = true
license = "MIT"
repository.workspace = true
description = "Derive macros for ReifyDB client"

[lib]
proc-macro = true

[dependencies]
reifydb-macro-impl = { workspace = true }
