[package]
name = "reifydb-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
license = "MIT"
repository.workspace = true
description = "Official Rust client library for ReifyDB"

[[example]]
name = "blocking_session"
path = "examples/blocking_ws.rs"

[[example]]
name = "callback_session"
path = "examples/callback_ws.rs"

[[example]]
name = "channel_session"
path = "examples/channel_ws.rs"

[features]
default = []

[dependencies]
reifydb-type = { workspace = true }
reifydb-hash = { workspace = true }
reifydb-client-derive = { workspace = true }

num-bigint = { version = "0.4.6", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.143" }

[dev-dependencies]
reifydb = { workspace = true, features = ["sub_server_http", "sub_server_ws"] }
reifydb-testing = { workspace = true }
test_each_file = { version = "0.3.5" }

