[package]
name = "reifydb-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
license = "MIT"
repository.workspace = true
description = "Official Rust client library for ReifyDB"

[[example]]
name = "http"
path = "examples/http.rs"

[[example]]
name = "websocket"
path = "examples/websocket.rs"

[features]
default = []

[dependencies]
reifydb-type = { workspace = true }
reifydb-client-derive = { workspace = true }

serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.143" }

# Async runtime
tokio = { workspace = true }

# HTTP client
reqwest = { workspace = true }

# WebSocket client
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true }

[dev-dependencies]
reifydb = { workspace = true, features = ["sub_server_http", "sub_server_ws"] }
reifydb-testing = { workspace = true }
test_each_file = { version = "0.3.5" }
tokio = { workspace = true }
