[package]
name = "reifydb-sub-admin"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Admin subsystem for web-based administration"

[dependencies]
reifydb-core = { workspace = true }
reifydb-engine = { workspace = true }
reifydb-sub-api = { workspace = true }
reifydb-type = { workspace = true }
reifydb-network = { workspace = true }

mio = { workspace = true }
slab = { workspace = true }
socket2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]