[package]
name = "engine"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base = { workspace = true }
rql = { workspace = true }
storage = { workspace = true }

log = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }

[dev-dependencies]