[package]
name = "reifydb-engine"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Query execution and processing engine for ReifyDB"

[dependencies]
reifydb-auth = { workspace = true }
reifydb-function = { workspace = true }
reifydb-catalog = { workspace = true }
reifydb-core = { workspace = true }
reifydb-abi = { workspace = true }
reifydb-hash = { workspace = true }
reifydb-rql = { workspace = true }
reifydb-rqlv2 = { workspace = true }
reifydb-store-transaction = { workspace = true }
reifydb-transaction = { workspace = true }
reifydb-type = { workspace = true }
reifydb-vm = { workspace = true }

tracing = { workspace = true }
postcard = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true }
indexmap = { workspace = true }
bumpalo = { workspace = true }
