[package]
name = "reifydb-core"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reifydb-type = { workspace = true }
crossbeam-channel = { workspace = true }
crossbeam-skiplist = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
uuid = { workspace = true }
num-bigint = { workspace = true }
bigdecimal = { workspace = true }
num-traits = { workspace = true }

[dev-dependencies]
reifydb-catalog = {workspace = true}
reifydb-cdc = {workspace = true}
reifydb-engine = {workspace = true}
reifydb-store-transaction = {workspace = true}
reifydb-transaction = {workspace = true}
