# Copyright (c) reifydb.com 2025
# This file is licensed under the AGPL-3.0-or-later, see license.md file

[package]
name = "reifydb-vm"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["trace"]
trace = []

[dependencies]
reifydb-core = { path = "../core" }
reifydb-type = { path = "../type" }
reifydb-engine = { path = "../engine" }
reifydb-catalog = { path = "../catalog" }

async-trait.workspace = true
futures-util.workspace = true
tokio-stream.workspace = true
thiserror = "2.0"

[dev-dependencies]
tokio = { workspace = true }
reifydb-store-transaction = { path = "../store-transaction" }
reifydb-transaction = { path = "../transaction" }
