# Copyright (c) reifydb.com 2025
# This file is licensed under the AGPL-3.0-or-later, see license.md file

[package]
name = "reifydb-vm"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["native", "trace"]
trace = []
native = [
    "trace",
    "reifydb-catalog/native",
    "reifydb-core/native",
    "reifydb-function/native",
    "reifydb-rqlv2/native",
    "reifydb-transaction/native",
    "reifydb-type/native",
]
wasm = [
    "trace",
    "reifydb-catalog/wasm",
    "reifydb-core/wasm",
    "reifydb-function/wasm",
    "reifydb-rqlv2/wasm",
    "reifydb-transaction/wasm",
    "reifydb-type/wasm",
]

[dependencies]
reifydb-catalog = { workspace = true }
reifydb-core = { workspace = true }
reifydb-function = { workspace = true }
reifydb-rqlv2 = { workspace = true }
reifydb-transaction = { workspace = true }
reifydb-type = { workspace = true }


[dev-dependencies]
reifydb-engine = { workspace = true, features = ["tokio"] }
reifydb-store-multi = { workspace = true, features = ["native"] }
reifydb-store-single = { workspace = true, features = ["native"] }
reifydb-transaction = { workspace = true, features = ["native"] }
