[package]
name = "reifydb-store-multi"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Multi-version storage for OLTP operations with MVCC support"

[features]
default = ["sqlite"]
sqlite = ["rusqlite"]

[build-dependencies]
reifydb-build = { workspace = true }

[dependencies]
reifydb-core = { workspace = true }
reifydb-runtime = { workspace = true }
reifydb-type = { workspace = true }

tracing = { workspace = true }
uuid = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rusqlite = { workspace = true, features = ["bundled"], optional = true }

[dev-dependencies]
test_each_file = { workspace = true }
reifydb-testing = { workspace = true }
