[package]
name = "reifydb-testing"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Testing utilities and helpers for ReifyDB"

[dependencies]
reifydb-core = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
test_each_file = { workspace = true }