[package]
name = "reifydb-testing"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Testing utilities and helpers for ReifyDB"

[features]
default = ["native"]
native = ["reifydb-core/native"]
wasm = ["reifydb-core/wasm"]

[dependencies]
reifydb-core = { workspace = true }
reifydb-type = {workspace = true}
uuid = { workspace = true }
tokio = {workspace = true}

[dev-dependencies]
test_each_file = { workspace = true }