[package]
name = "reifydb-store-column"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Column-oriented storage for analytical queries in ReifyDB"

[dependencies]
reifydb-core = { workspace = true }
reifydb-type = { workspace = true }
reifydb-compression = { workspace = true }

crossbeam-skiplist = { workspace = true }
