[package]
name = "reifydb-transaction"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Transaction management and concurrency control for ReifyDB"

[features]
test-stress = []
worker_pool = []

[dependencies]
reifydb-core = { workspace = true }
reifydb-store-transaction = { workspace = true }
reifydb-type = { workspace = true }

crossbeam-channel = { workspace = true }
crossbeam-skiplist = { workspace = true }
indexmap = { workspace = true }
parking_lot = { workspace = true }
self_cell = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
futures-executor = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true }


[dev-dependencies]
reifydb-testing = { workspace = true }
reifydb-engine = { workspace = true }
test_each_file = { workspace = true }
