[package]
name = "transaction"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base = { workspace = true }
persistence = { workspace = true }

serde = { workspace = true }
serde_bytes = { workspace = true }

[dev-dependencies]
testing = { workspace = true }
test_each_file = { workspace = true }
