[package]
name = "reifydb-transaction"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Transaction management and concurrency control for ReifyDB"

[features]
default = []
test-stress = []
worker_pool = []

[build-dependencies]
reifydb-build = { workspace = true }

[dependencies]
reifydb-core = { workspace = true }
reifydb-store-multi = { workspace = true }
reifydb-store-single = { workspace = true }
reifydb-type = { workspace = true }
reifydb-runtime = { workspace = true }

thiserror = { workspace = true }
crossbeam-skiplist = { workspace = true }
indexmap = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
crossbeam-channel = { workspace = true }

[dev-dependencies]
reifydb-testing = { workspace = true }
reifydb-engine = { workspace = true, features = ["tokio"] }
test_each_file = { workspace = true }
