[package]
name = "reifydb-transaction"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Transaction management and concurrency control for ReifyDB"

[features]
default = ["native"]
native = ["reifydb-runtime/native", "reifydb-hash/native", "crossbeam-channel"]
wasm = ["reifydb-runtime/wasm", "reifydb-hash/wasm"]
test-stress = []
worker_pool = []

[dependencies]
reifydb-core = { workspace = true }
reifydb-hash = { workspace = true }
reifydb-store-multi = { workspace = true }
reifydb-store-single = { workspace = true }
reifydb-type = { workspace = true }
reifydb-runtime = { workspace = true }

crossbeam-channel = { workspace = true, optional = true }
crossbeam-skiplist = { workspace = true }
indexmap = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }


[dev-dependencies]
reifydb-testing = { workspace = true }
reifydb-engine = { workspace = true }
test_each_file = { workspace = true }
