[package]
name = "reifydb-sub-api"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Subsystem API and interfaces for ReifyDB"

[dependencies]
reifydb-core = { workspace = true }
reifydb-engine = { workspace = true }
reifydb-type = { workspace = true }

[dev-dependencies]
reifydb-store-transaction = { workspace = true}
reifydb-transaction = { workspace = true}