[package]
name = "reifydb-flow-operator-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "SDK for building flow operators in ReifyDB"

[dependencies]
reifydb-flow-operator-abi = { workspace = true }
reifydb-core = { workspace = true}
reifydb-type = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
