[package]
name = "reifydb-flow-operator-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
reifydb-flow-operator-abi = { workspace = true }
reifydb-core = { workspace = true}
reifydb-type = { workspace = true }

[dev-dependencies]
